apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vkpr.fullname" . }}
  labels:
    {{- include "vkpr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.whoami.replicaCount }}
  selector:
    matchLabels:
      {{- include "vkpr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vkpr.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.whoami.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.whoami.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.whoami.securityContext | nindent 12 }}
          image: "{{ .Values.whoami.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.whoami.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.whoami.resources | nindent 12 }}
      {{- with .Values.whoami.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.whoami.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.whoami.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
