{{- if .Values.keycloak.enabled -}}
{{- if eq .Values.keycloak.postgresql.enabled false -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end -}}
{{- end -}}
