# Whoami app with real DNS
# Guide: https://vertigobr.github.io/vkpr-docs/docs/guides/local/certs-dns

# The guide covers:
# - Ingress controller (ingress-nginx)
# - Whoami app with real DNS
# - Cert-Manager
# - External DNS

# INGRESS STACK
ingress-nginx:
  enabled: true

external-dns:
  enabled: true
  rbac:
    create: true
  sources:
  - ingress
  provider: digitalocean
  interval: "1m"
  logLevel: debug

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
  - host: whoami.vkpr-dev.vertigo.com.br
    paths: ["/"]
  tls:
  - hosts:
    - whoami.vkpr-dev.vertigo.com.br
    secretName: whoami-cert

# SECURITY STACK
cert-manager:
  enabled: true
  installCRDs: false # ok for testing
  ingressShim:
    defaultIssuerName: letsencrypt-staging
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  prometheus:
    enabled: false
