# Basic installation
# Guide: https://vertigobr.github.io/vkpr-docs/docs/guides/local/basic-installation

# The guide covers:
# - Ingress controller (ingress-nginx)
# - Whoami app


# INGRESS STACK
ingress-nginx:
  enabled: true

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
  - host: whoami.localdomain
    paths: ["/"]
