# View applications logs with Loki and Grafana
# Guide: https://vertigobr.github.io/vkpr-docs/docs/guides/local/loki-grafana

# The guide covers:
# - Ingress controller (ingress-nginx)
# - Whoami app
# - Loki
# - Grafana
# - Prometheus

# INGRESS STACK
ingress-nginx:
  enabled: true

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
  - host: whoami.localdomain
    paths: ["/"]

# LOGGING STACK:
loki-stack:
  enabled: true
  grafana:
    enabled: false

# MONITORING STACK
kube-prometheus-stack:
  enabled: true
  prometheusOperator:
    enabled: true
    createCustomResource: false
    cleanupCustomResource: false
  prometheus:
    enabled: true
  alertmanager:
    enabled: false
  grafana:
    enabled: true
    sidecar:
      datasources:
        enabled: true
    persistence:
      enabled: false
    ingress:
      enabled: true
      hosts:
      - vkpr-grafana.default.svc
  ## Component scraping the kube api server
  kubeApiServer:
    enabled: true
  ## Component scraping the kubelet and kubelet-hosted cAdvisor
  kubelet:
    enabled: true
  ## Component scraping the kube controller manager
  kubeControllerManager:
    enabled: true
  ## Component scraping coreDns. Use either this or kubeDns
  coreDns:
    enabled: true
  ## Component scraping kubeDns. Use either this or coreDns
  kubeDns:
    enabled: false
  ## Component scraping etcd
  kubeEtcd:
    enabled: true
  ## Component scraping kube scheduler
  kubeScheduler:
    enabled: true
  ## Component scraping kube proxy
  kubeProxy:
    enabled: true
  ## Component scraping kube state metrics
  kubeStateMetrics:
    enabled: true
