apiVersion: v2
name: vkpr
version: 0.8.4
appVersion: v1.4.0
home: https://github.com/vertigobr/vkpr
icon: https://vertigo.com.br/wp-content/uploads/favicon.png
description: VKPR Helm chart (Vertigo Kubernetes Production Runtime)
keywords:
  - vkpr
  - production runtime
maintainers:
  - name: Vertigo
    email: devops@vertigo.com.br
    url: https://vertigo.com.br
sources:
  - https://github.com/vertigobr/vkpr
dependencies:
  ### INGRESS STACK ###
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 3.7.1
    condition: nginx-ingress.enabled
    alias: nginx-ingress
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 3.4.9
    condition: external-dns.enabled

  ### LOGGING STACK ###
  - name: loki-stack
    repository: https://grafana.github.io/loki/charts
    version: 2.0.0
    condition: loki-stack.enabled

  ### MONITORING STACK ###
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 10.3.1
    condition: kube-prometheus-stack.enabled
  - name: jaeger
    repository: https://jaegertracing.github.io/helm-charts
    version: 0.39.0
    condition: jaeger.enabled

  ### SECURITY STACK ###
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.2.0
    condition: cert-manager.enabled
  - name: keycloak
    repository: https://codecentric.github.io/helm-charts
    version: 9.5.0
    condition: keycloak.enabled
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.8.0
    condition: vault.enabled

  ### BACKUP STACK ###
  - name: velero
    repository: https://vmware-tanzu.github.io/helm-charts/
    version: 2.13.3
    condition: velero.enabled
